### ISSUE TITLE
zazzle link is no more working

### ISSUE THREAD

**Issue by aschheim** [ORCID/qrorcid#5]
got this message at zazzle page:
The product that you have requested is unavailable. This is likely because:
You do not have access to the product ,
The product ID is not valid, or
The product was deleted

**Comment by wjrsimpson** [comment]
Hi Aschheim,

Thanks for the heads up!

There was a problem with printing the larger size stickers, so Zazzle disabled the product. I have now configured the product so that the only option is the smaller size stickers, which should be OK.

I have enabled the product, so the link should work for you now.

It's great if you want to buy the stickers, but you can also download the QR code for free by clicking the large QR code image below the Zazzle link.

Best regards,

Will
